name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0-278.1.beta

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.6.0
  
  # Firebase - mantener tus versiones originales
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  
  # HTTP para la API de Sportradar
  http: ^1.1.0
  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Solución: Forzar versiones específicas que funcionen
dependency_overrides:
  js: ^0.6.7
  web: ^0.5.1
  meta: ^1.12.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/sports/
    - assets/logos/teams/