name: myapp
description: "EpicSports - MLB en tiempo real"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0-278.1.beta

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.6.0
  
  # 🔥 FIREBASE - Versiones estables y compatibles
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9
  
  # 🔔 NOTIFICACIONES - Versiones compatibles
  firebase_messaging: ^14.7.19
  flutter_local_notifications: ^17.0.0
  
  # HTTP para la API de Sportradar
  http: ^1.1.0
  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# 🔧 DEPENDENCY OVERRIDES - Para resolver conflictos
dependency_overrides:
  js: ^0.6.7
  web: ^0.5.1
  meta: ^1.12.0
  # Forzar versiones compatibles
  firebase_core_platform_interface: ^5.0.0
  collection: ^1.18.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/sports/
    - assets/logos/teams/